### ISSUE TITLE
Support for organization projects

### ISSUE THREAD

**Issue by douglaslassance** [skeet70/default-project-board-action#6] opened 2021-05-15 00:20 UTC
Add the ability to add newly created issues to an organization project.
Maybe this is supported already, in which case a snippet would be nice. Otherwise, it would be a nice addition.

**Comment by skeet70** [comment] 2024-05-07 17:57
That's a good idea, PRs would be welcome for it.

**Comment by skeet70** [comment] 2024-05-07 18:01
Looks like this is a duplicate of #5

**Closed as completed by skeet70** 2024-05-07 18:01 UTC
